services:
  - type: web
    name: banking-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: MONGODB_URI
        sync: false # Set the value in the Render dashboard for security 